//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int id { get; set; }
        public string page_name { get; set; }
        public string content_footer { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string author_name { get; set; }
    }
}
