//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string duration { get; set; }
        public string customer_amount { get; set; }
        public string description { get; set; }
        public string review { get; set; }
        public string price { get; set; }
        public string img_link { get; set; }
        public string link { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> databegin { get; set; }
        public string area { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
